fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    nodejs: "https://github.com/puppetlabs/puppetlabs-nodejs.git"
    supervisor: "https://github.com/proletaryo/puppet-supervisor.git"
  symlinks:
    ghost: "#{source_dir}"
